# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Lab of Theoretical Biology
tagline:          理論生物學實驗室
description:      "Computational Biology"
url:              https://github.com/labtheobio/labtheobio.github.io
baseurl:          /

author:
  name:           'LabTheoBio'
  url:            https://twitter.com/labtheobio

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/labtheobio/labtheobio.github.io
